repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: env PYTHONPATH="." python -m pylint assembler/
        language: system
        always_run: true
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: env PYTHONPATH="." python -m mypy assembler/
        language: system
        always_run: true
        pass_filenames: false
