name: Unit Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.0'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint
        python -m pip install mypy
    - name: Lint
      run: python -m pylint assembler/
    - name: Check types
      run: python -m mypy assembler/